# Generated by Django 5.2.1 on 2025-06-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamgroup', '0002_remove_team_created_at_team_description_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
